"""empty message

Revision ID: 2e9a94155e29
Revises: None
Create Date: 2016-03-13 16:31:49.232941

"""

# revision identifiers, used by Alembic.
revision = '2e9a94155e29'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'bio')
    ### end Alembic commands ###
