"""empty message

Revision ID: 5cf268f8c493
Revises: 2e9a94155e29
Create Date: 2016-03-15 12:16:46.826336

"""

# revision identifiers, used by Alembic.
revision = '5cf268f8c493'
down_revision = '2e9a94155e29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', u'cover_photo', u'photo')
    op.alter_column('user', u'avatar', u'photo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', u'photo', u'cover_photo')
    op.alter_column('user', u'photo', u'avatar')
    ### end Alembic commands ###
